---
title: "Attendance Policy Evaluation"
format: gfm
---

## Description

This project evaluates the effectiveness of High School A's attendance policy implemented during the first trimester of the 2024-2025 school year. Not only can we compare the change in attendance from the first trimester to the previous year’s attendance at High School A, the implementation of the policy by High School A alone serves as a kind of natural experiment, allowing comparison to High School B’s attendance during the same trimester where High School B serves as a control group. We will evaluate how the attendance policy has impacted different groups of students (e.g., demographic/income splits) by these same comparisons in and across high schools.

## Project Organization

- `/code` Scripts with prefixes (e.g., `01_import-data.py`, `02_clean-data.py`) and functions in `/code/src`.
- `/data` Simulated and real data, the latter not pushed.
- `/figures` PNG images and plots.
- `/output` Output from model runs, not pushed.
- `/private` A catch-all folder for miscellaneous files, not pushed.
- `/.venv` Hidden project library, not pushed.
- `.gitignore` Hidden Git instructions file.
- `.python-version` Hidden Python version file.
- `pyproject.toml` Project environment configuration file.
- `uv.lock` Project environment lock file.

## Project Environment

After cloning this repository, go to the project's terminal in Positron and run `uv run` to create the `/.venv` project library and install the specified Python and library versions.

For more details on using Python, Positron, GitHub, Quarto, etc. see the recommended [Data Stack](https://github.com/marcdotson/data-stack).

